[package]
name = "bat"
version = "0.1.0"
edition = "2024"

[dependencies]
atomic_float = "1.1.0"
cpal = "0.16.0"
crossbeam-channel = "0.5.15"
eframe = "0.33.0"
egui = "0.33.0"
egui_extras = "0.33.0"
egui_plot = "0.34.0"
realfft = "3.5.0"
rtrb = "0.3.2"
